services:
  ollamactl-api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ollamactl_api
    restart: unless-stopped
    ports:
      - "100.114.205.53:8700:8700"
    volumes:
      - /docker/ollamactl:/data
    env_file:
      - .env
    networks:
      - ollamactl_net

  ollamactl-ui:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ollamactl_ui
    restart: unless-stopped
    ports:
      - "100.114.205.53:8701:80"
    networks:
      - ollamactl_net

networks:
  ollamactl_net:
    driver: bridge
