services:
  stackctl-api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: stackctl_api
    restart: unless-stopped
    ports:
      - "100.114.205.53:8700:8700"
    volumes:
      - ./ssh:/opt/stackctl/ssh:ro
      - /docker/stackctl:/data
    env_file:
      - .env
    networks:
      - stackctl_net

  stackctl-ui:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: stackctl_ui
    restart: unless-stopped
    ports:
      - "100.114.205.53:8701:80"
    networks:
      - stackctl_net

networks:
  stackctl_net:
    driver: bridge
